# Generated by Django 4.0.2 on 2022-04-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Products_type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('Product_tit', models.TextField(max_length=400)),
                ('product_image', models.ImageField(upload_to='images')),
                ('Products_ID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
