# Generated by Django 4.0.2 on 2022-04-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='Price',
        ),
        migrations.AlterField(
            model_name='products',
            name='Product_tit',
            field=models.CharField(max_length=400),
        ),
    ]
